version: '3.7'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    # command: python manage.py runserver [::]:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app:rw
      - static_volume:/home/nalo/app/static
    depends_on:
      - pg_db
    ports:
      - 8001:8001
    # networks:
    #   - web
      # - node_socket
    env_file:
      - .env

  pg_db:
    env_file:
      - .env
    image: postgres:latest
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    volumes:
        - postgres_data:/tmp/pgdata
    ports:
      - "5432:5432"
 

# networks:
#   web:
  # node_socket:

volumes:
  static_volume:
  postgres_data:
  